import type { Deck, GameState } from "./types";

export const MIN_CARD_VALUE = 1;
export const MAX_CARD_VALUE = 13;

export const INITIAL_DECK_COUNTS: Deck = {
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 1,
};

export const INITIAL_STATE: GameState = {
  bestScore: 0,
  previousRunScore: 0,
  pendingBonuses: [],
  pendingGreedItBonus: null,
  streak: 0,
  runStatus: "IDLE",
  score: 0,
  bench: [],
  benchOnFire: false,
  discardUsesLeft: 1,
  deck: { ...INITIAL_DECK_COUNTS },
  flipCount: 0,
  selfOvertakeTriggered: false,
  benchCompleteTriggered: false,
  bonusOffer: null,
  bonusChoiceLocked: false,
  activeBonuses: {
    peekUsesLeft: 0,
    doubleUsesLeft: 0,
    doubleNextFlipArmed: false,
    swanShieldAvailable: false,
    deckSmartEnabled: false,
    flipSafeUsesLeft: 0,
    flipSafeArmed: false,
    resetForcedUsesLeft: 0,
    friday13Available: false,
    onycActive: false,
    doubleDrawUsesLeft: 0,
    fuegoooEnabled: false,
    precisionArmed: false,
    goldShieldAvailable: false,
  },
  nextCardPreview: null,
  goldCap: 3,
  goldDrawnCount: 0,
  goldDrawnIds: [],
  goldDeck: {},
  lastNormalValue: null,
  chainPending: false,
  pariPendingFlip: false,
  lastFlipKind: null,
  greedItOverride: false,
  streakMultiplier: 1,
  destinyFlipsLeft: 0,
  greedItOffered: false,
  greedItResolved: false,
  giPlus5Active: false,
  giTripleBonusActive: false,
  giGoldPlusActive: false,
};
